#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/Create.cshtml")]
    public partial class _Views_Company_Create_cshtml : System.Web.Mvc.WebViewPage<Advertise.ViewModel.Models.Companies.CompanyCreateViewModel>
    {
        public _Views_Company_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Company\Create.cshtml"
 using (Html.BeginForm(MVC.Company.Create(), FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\Company\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\Company\Create.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">ثبت شرکت</h3>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 15 "..\..\Views\Company\Create.cshtml"
           Write(Html.ValidationSummary(true, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.Code, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 20 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.Code, new {htmlAttributes = new {@class = "form-control"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 21 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Code, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.BrandName, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 28 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.BrandName, new {htmlAttributes = new {@class = "form-control"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 29 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.BrandName, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.Email, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 37 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 42 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.WebSite, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 44 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.WebSite, new {htmlAttributes = new {@class = "form-control"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 45 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.WebSite, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 50 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.PhoneNumber, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 52 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.PhoneNumber, new {htmlAttributes = new {@class = "form-control"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 53 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.PhoneNumber, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 58 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.MobileNumber, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 60 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.MobileNumber, new {htmlAttributes = new {@class = "form-control"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 61 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.MobileNumber, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 67 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.EmployeeCount, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 69 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.EmployeeCount, new {htmlAttributes = new {@class = "form-control"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 70 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.EmployeeCount, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 75 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.LogoFileName, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10 k-rtl\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"ImageFileName\"");

WriteLiteral(" name=\"ImageFileName\"");

WriteLiteral(" accept=\".jpg,.png\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 78 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.LogoFileName, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">پیش نمایش</label>\r\n                    ");

WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4636), Tuple.Create("\"", 4671)
, Tuple.Create(Tuple.Create("", 4642), Tuple.Create<System.Object, System.Int32>(Href("~/Files/Avatar/no-preview.png")
, 4642), false)
);

WriteLiteral(" id=\"ImagePreview\"");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"300\"");

WriteLiteral(" height=\"300\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 90 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.Body, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10 k-rtl\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"Body\"");

WriteLiteral(" name=\"Body\"");

WriteLiteral(" rows=\"10\"");

WriteLiteral(" cols=\"30\"");

WriteLiteral(" style=\"height: 440px\"");

WriteLiteral("></textarea>\r\n");

WriteLiteral("                        ");

            
            #line 93 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Body, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 98 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.EstablishedOn , new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10 k-rtl\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 100 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.EstablishedOn, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 101 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.EstablishedOn, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 106 "..\..\Views\Company\Create.cshtml"
               Write(Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10 k-rtl\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 108 "..\..\Views\Company\Create.cshtml"
                   Write(Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 109 "..\..\Views\Company\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n\r\n\r\n            </div>\r\n " +
"       </div>\r\n\r\n    </div>\r\n");

            
            #line 119 "..\..\Views\Company\Create.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ثبت\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 128 "..\..\Views\Company\Create.cshtml"
           Write(Html.ActionLink("برگشت به لیست", "List", new { Controller = "Company" }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 132 "..\..\Views\Company\Create.cshtml"
   


}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
