#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/Delete.cshtml")]
    public partial class _Views_Company_Delete_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Company_Delete_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Company\Delete.cshtml"
Write(Model);

            
            #line default
            #line hidden
WriteLiteral(" Advertise.ViewModel.Models.Companies.CompanyDeleteViewModel\r\n");

            
            #line 2 "..\..\Views\Company\Delete.cshtml"
  
    ViewBag.title = "حذف";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Company\Delete.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Company\Delete.cshtml"
     using (Html.BeginForm(MVC.Company.Delete(), FormMethod.Post))
     {
         
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Company\Delete.cshtml"
    Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Company\Delete.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n             <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                 <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">حذف دسته</h3>\r\n             </div>\r\n\r\n             <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n                 <h3>آیا برای حذف اطمینان دارید؟</h3>\r\n                 <div" +
">\r\n                     <hr/>\r\n                     <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n\r\n\r\n                         ");

WriteLiteral("\r\n\r\n\r\n\r\n                     </dl>\r\n\r\n                 </div>\r\n\r\n             </d" +
"iv>\r\n\r\n             <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                 <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                     <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                         <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"حذف\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("/>\r\n                     </div>\r\n\r\n                     <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                         ");

            
            #line 46 "..\..\Views\Company\Delete.cshtml"
                    Write(Html.ActionLink("برگشت به لیست", "List", new {Controller = "Company"}, new {@class = "btn btn-default"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                     </div>\r\n                 </div>\r\n             </div>\r\n\r\n  " +
"       </div>\r\n");

            
            #line 52 "..\..\Views\Company\Delete.cshtml"

     }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
