#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/Item.cshtml")]
    public partial class _Views_Company_Item_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Advertise.ViewModel.Models.Companies.CompanyListViewModel>>
    {
        public _Views_Company_Item_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Company\Item.cshtml"
  
    ViewBag.Title = "مشاهده";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">مشاهده شرکت ها </h3>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Views\Company\Item.cshtml"
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Company\Item.cshtml"
             foreach (var item in Model)
            {


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-sm-6 col-md-4\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumbnail\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Company\Item.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Company\Item.cshtml"
                         if (System.IO.File.Exists(  Request.MapPath("~/Uploads/" + @item.LogoFileName )))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 638), Tuple.Create("\"", 672)
, Tuple.Create(Tuple.Create("", 644), Tuple.Create<System.Object, System.Int32>(Href("~/Uploads/")
, 644), false)
            
            #line 23 "..\..\Views\Company\Item.cshtml"
, Tuple.Create(Tuple.Create("", 654), Tuple.Create<System.Object, System.Int32>(item.LogoFileName
            
            #line default
            #line hidden
, 654), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 673), Tuple.Create("\"", 697)
            
            #line 23 "..\..\Views\Company\Item.cshtml"
, Tuple.Create(Tuple.Create("", 679), Tuple.Create<System.Object, System.Int32>(item.LogoFileName
            
            #line default
            #line hidden
, 679), false)
);

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"300\"");

WriteLiteral(" height=\"300\"");

WriteLiteral(">\r\n");

            
            #line 24 "..\..\Views\Company\Item.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 864), Tuple.Create("\"", 899)
, Tuple.Create(Tuple.Create("", 870), Tuple.Create<System.Object, System.Int32>(Href("~/Files/Avatar/no-preview.png")
, 870), false)
);

WriteLiteral(" alt=\"no\"");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"300\"");

WriteLiteral(" height=\"300\"");

WriteLiteral(">\r\n");

            
            #line 28 "..\..\Views\Company\Item.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">\r\n                            <h3>");

            
            #line 31 "..\..\Views\Company\Item.cshtml"
                           Write(Html.DisplayFor(itemModel => item.BrandName ));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                            <p>");

            
            #line 32 "..\..\Views\Company\Item.cshtml"
                          Write(Html.DisplayFor(itemModel => item.Email));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p>");

            
            #line 33 "..\..\Views\Company\Item.cshtml"
                          Write(Html.DisplayFor(itemModel => item.WebSite));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n                            <p>\r\n");

WriteLiteral("                                ");

            
            #line 36 "..\..\Views\Company\Item.cshtml"
                           Write(Html.ActionLink("جزییات", "Details", new {id = item.Id}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" role=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-heart\"");

WriteLiteral("></i> </a>\r\n                            </p>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n");

            
            #line 42 "..\..\Views\Company\Item.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 52 "..\..\Views\Company\Item.cshtml"
           Write(Html.ActionLink("برگشت به لیست", "List", new { Controller = "Company" }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
