#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/List.cshtml")]
    public partial class _Views_Company_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Advertise.ViewModel.Models.Companies.CompanyListViewModel>>
    {
        public _Views_Company_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Company\List.cshtml"
  
    ViewBag.Title = "List";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>List</h2>\r\n\r\n<p>\r\n    <a href =\"#\" class=\"btn btn-primary\" onclick =\"Crea" +
"te()\">افزودن نعت</a>\r\n</p>\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.BrandName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.LogoFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.BackgroundFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 33 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.MobileNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 39 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.WebSite));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 42 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.EmployeeCount));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayNameFor(model => model.EstablishedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 50 "..\..\Views\Company\List.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 53 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 56 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.BrandName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 59 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 62 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.LogoFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 65 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.BackgroundFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 68 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 71 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.MobileNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 74 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 77 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.WebSite));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 80 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.EmployeeCount));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 83 "..\..\Views\Company\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.EstablishedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 86 "..\..\Views\Company\List.cshtml"
       Write(Html.ActionLink("Edit", "Edit", new {  id=item.Id  }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 87 "..\..\Views\Company\List.cshtml"
       Write(Html.ActionLink("Details", "Details", new {  id=item.Id  }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 88 "..\..\Views\Company\List.cshtml"
       Write(Html.ActionLink("Delete", "Delete", new {  id=item.Id  }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 91 "..\..\Views\Company\List.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n<!-- Modal -->\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"myModal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">Modal title</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" id =\"Bodymodal\">\r\n                ...\r\n            </div>\r\n            \r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral(@"
    <script >
        function Create() {
            $.ajax({
                url: ""/Company/Create"",
                type: ""Get"",
                date: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('افزودن شرکت جدید');
                $('#Bodymodal').html(result);

            });
        }
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
