#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/List.cshtml")]
    public partial class _Views_Company_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Advertise.ViewModel.Models.Companies.CompanyListViewModel>>
    {
        public _Views_Company_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Company\List.cshtml"
  
    ViewBag.Title = "لیست";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">لیست شرکت ها</h3>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n        <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n            <tr>\r\n\r\n\r\n\r\n\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Views\Company\List.cshtml"
               Write(Html.DisplayNameFor(model => model.BrandName ));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n\r\n\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\Company\List.cshtml"
               Write(Html.DisplayNameFor(model => model.Email ));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Views\Company\List.cshtml"
               Write(Html.DisplayNameFor(model => model.MobileNumber ));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n\r\n                <th></th>\r\n            </tr>\r\n\r\n");

            
            #line 45 "..\..\Views\Company\List.cshtml"
            
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Company\List.cshtml"
             foreach (var item in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n\r\n\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 51 "..\..\Views\Company\List.cshtml"
                   Write(Html.DisplayFor(modelItem => item.BrandName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n\r\n\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 56 "..\..\Views\Company\List.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 60 "..\..\Views\Company\List.cshtml"
                   Write(Html.DisplayFor(modelItem => item.MobileNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n\r\n                    <td>\r\n\r\n                      " +
"  <a");

WriteLiteral(" class=\"btn-sm btn btn-default\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1536), Tuple.Create("\"", 1582)
            
            #line 65 "..\..\Views\Company\List.cshtml"
, Tuple.Create(Tuple.Create("", 1543), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Company .Edit(item.Id))
            
            #line default
            #line hidden
, 1543), false)
);

WriteLiteral("\r\n                           type=\"button\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n                            ویرایش\r\n                        </a>\r\n        " +
"                |\r\n                        <a");

WriteLiteral(" class=\"btn-sm btn btn-default\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1834), Tuple.Create("\"", 1882)
            
            #line 71 "..\..\Views\Company\List.cshtml"
, Tuple.Create(Tuple.Create("", 1841), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Company.Details(item.Id))
            
            #line default
            #line hidden
, 1841), false)
);

WriteLiteral("\r\n                           type=\"button\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-info-circle\"");

WriteLiteral("></i>\r\n                            جزییات\r\n                        </a>\r\n        " +
"                |\r\n                        <a");

WriteLiteral(" class=\"btn-sm btn btn-danger\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2140), Tuple.Create("\"", 2187)
            
            #line 77 "..\..\Views\Company\List.cshtml"
, Tuple.Create(Tuple.Create("", 2147), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Company.Delete(item.Id))
            
            #line default
            #line hidden
, 2147), false)
);

WriteLiteral("\r\n                           type=\"button\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-trash-o\"");

WriteLiteral("></i>\r\n                            حذف\r\n                        </a>\r\n\r\n         " +
"           </td>\r\n\r\n                </tr>\r\n");

            
            #line 86 "..\..\Views\Company\List.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </table>\r\n\r\n\r\n\r\n    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 98 "..\..\Views\Company\List.cshtml"
           Write(Html.ActionLink("ایجاد جدید", "Create", new { Controller = "Company" }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 101 "..\..\Views\Company\List.cshtml"
           Write(Html.ActionLink("مشاهده شرکت ها", "Item", new { Controller = "Company" }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
