#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/Create.cshtml")]
    public partial class _Views_Category_Create_cshtml : System.Web.Mvc.WebViewPage<Advertise.ViewModel.Models.Categories.CategoryCreateViewModel>
    {
        public _Views_Category_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Category\Create.cshtml"
  
    ViewBag.Title = "ایجاد";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Category\Create.cshtml"
 using (Html.BeginForm(MVC.Category.Create(),FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Category\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Category\Create.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">ایجاد دسته جدید</h3>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\Category\Create.cshtml"
           Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Views\Category\Create.cshtml"
               Write(Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 25 "..\..\Views\Category\Create.cshtml"
                   Write(Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 26 "..\..\Views\Category\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                \r\n         " +
"       <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\Category\Create.cshtml"
               Write(Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 33 "..\..\Views\Category\Create.cshtml"
                   Write(Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 34 "..\..\Views\Category\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Views\Category\Create.cshtml"
               Write(Html.LabelFor(model => model.ParentId, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"k-rtl\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" id=\"getCategoryList\"");

WriteLiteral("></div>\r\n                        </div>\r\n");

WriteLiteral("                        ");

            
            #line 44 "..\..\Views\Category\Create.cshtml"
                   Write(Html.HiddenFor(model => model.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 45 "..\..\Views\Category\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.ParentId, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 50 "..\..\Views\Category\Create.cshtml"
               Write(Html.LabelFor(model => model.ImageFileName, new {@class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10 k-rtl\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"ImageFileName\"");

WriteLiteral(" name=\"ImageFileName\"");

WriteLiteral(" accept=\".jpg,.png\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 53 "..\..\Views\Category\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.ImageFileName, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 58 "..\..\Views\Category\Create.cshtml"
               Write(Html.LabelFor(model => model.ImageFileName,"پیش نمایش", new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"#\"");

WriteLiteral(" id=\"ImagePreview\"");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"300\"");

WriteLiteral(" height=\"300\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 65 "..\..\Views\Category\Create.cshtml"
               Write(Html.LabelFor(model => model.Body, new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10 k-rtl\"");

WriteLiteral(">\r\n                            <textarea");

WriteLiteral(" id=\"Body\"");

WriteLiteral(" name=\"Body\"");

WriteLiteral(" rows=\"10\"");

WriteLiteral(" cols=\"30\"");

WriteLiteral(" style=\"height: 440px\"");

WriteLiteral("></textarea>\r\n");

WriteLiteral("                        ");

            
            #line 68 "..\..\Views\Category\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Body, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                \r\n       " +
"     </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                \r\n                <div");

WriteLiteral(" class=\"col-md-offset-1 col-md-1\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ثبت\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 84 "..\..\Views\Category\Create.cshtml"
               Write(Html.ActionLink("برگشت به لیست", "List",new {Controller="Category"},new {@class="btn btn-default"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 89 "..\..\Views\Category\Create.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
