#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/Delete.cshtml")]
    public partial class _Views_Category_Delete_cshtml : System.Web.Mvc.WebViewPage<Advertise.ViewModel.Models.Categories.CategoryDeleteViewModel>
    {
        public _Views_Category_Delete_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 25 "..\..\Views\Category\Delete.cshtml"
  
    ViewBag.Title = "حذف";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Delete</h2>\r\n\r\n\r\n<h3>آیا برای حذف اطمینان دارید؟؟</h3>\r\n<div>\r\n    <h4>Ca" +
"tegoryDeleteViewModel</h4>\r\n    <hr />\r\n    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 41 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayFor(model => model.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 51 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 55 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 61 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 65 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 71 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.ImageFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 75 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayFor(model => model.ImageFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 81 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.ParentPath));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 85 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayFor(model => model.ParentPath));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 91 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 95 "..\..\Views\Category\Delete.cshtml"
       Write(Html.DisplayFor(model => model.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n\r\n    </dl>\r\n\r\n");

            
            #line 101 "..\..\Views\Category\Delete.cshtml"
    
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Category\Delete.cshtml"
     using (Html.BeginForm()) {
        
            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Category\Delete.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Category\Delete.cshtml"
                                


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-actions no-color\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Delete\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" /> |\r\n");

WriteLiteral("            ");

            
            #line 106 "..\..\Views\Category\Delete.cshtml"
       Write(Html.ActionLink("برگشت به لیست", "List"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 108 "..\..\Views\Category\Delete.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
