#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/Delete.cshtml")]
    public partial class _Views_Category_Delete_cshtml : System.Web.Mvc.WebViewPage<Advertise.ViewModel.Models.Categories.CategoryDeleteViewModel>
    {
        public _Views_Category_Delete_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Category\Delete.cshtml"
  
    ViewBag.Title = "حذف";


            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Category\Delete.cshtml"
 using (Html.BeginForm(MVC.Category.Delete(), FormMethod.Post))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Category\Delete.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Category\Delete.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">حذف دسته</h3>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n            <h3>آیا برای حذف اطمینان دارید؟</h3>\r\n            <div>\r\n       " +
"         <hr/>\r\n                <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n\r\n\r\n                    <dt>\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Views\Category\Delete.cshtml"
                   Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </dt>\r\n                    <dd>\r\n");

WriteLiteral("                        ");

            
            #line 30 "..\..\Views\Category\Delete.cshtml"
                   Write(Html.DisplayFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </dd>\r\n\r\n\r\n\r\n                </dl>\r\n\r\n            </div>\r\n\r" +
"\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"حذف\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("/>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Views\Category\Delete.cshtml"
               Write(Html.ActionLink("برگشت به لیست", "List", new {Controller = "Category"}, new {@class = "btn btn-default"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n");

            
            #line 55 "..\..\Views\Category\Delete.cshtml"
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
