#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/Item.cshtml")]
    public partial class _Views_Category_Item_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Advertise.ViewModel.Models.Categories.CategoryListViewModel>>
    {
        public _Views_Category_Item_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Category\Item.cshtml"
  
    ViewBag.Title = "Item";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Item</h2>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\Category\Item.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Category\Item.cshtml"
     foreach (var item in Model)
    {


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-6 col-md-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"thumbnail\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"#\"");

WriteLiteral(" alt=\"...\"");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">\r\n                    <h3>");

            
            #line 16 "..\..\Views\Category\Item.cshtml"
                   Write(Html.DisplayFor(itemModel => item.Title));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                    <p>");

            
            #line 17 "..\..\Views\Category\Item.cshtml"
                  Write(Html.DisplayFor(itemModel => item.Description));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    <p>\r\n");

WriteLiteral("                        ");

            
            #line 19 "..\..\Views\Category\Item.cshtml"
                   Write(Html.ActionLink("جزییات", "Details", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\Category\Item.cshtml"
                                                                     Write(Html.DisplayFor(itemModel => item.Code));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    </p>\r\n                </div>\r\n            </div>\r\n     " +
"   </div>\r\n");

            
            #line 25 "..\..\Views\Category\Item.cshtml"

    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
