#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/List.cshtml")]
    public partial class _Views_Category_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Advertise.ViewModel.Models.Categories.CategoryListViewModel>>
    {
        public _Views_Category_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Category\List.cshtml"
  
    ViewBag.Title = "لیست";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">لیست دسته ها</h3>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n        <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n            <tr>\r\n\r\n\r\n\r\n\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Category\List.cshtml"
               Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n\r\n\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Views\Category\List.cshtml"
               Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\Category\List.cshtml"
               Write(Html.DisplayNameFor(model => model.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n\r\n                <th></th>\r\n            </tr>\r\n\r\n");

            
            #line 40 "..\..\Views\Category\List.cshtml"
            
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Category\List.cshtml"
             foreach (var item in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n\r\n\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 46 "..\..\Views\Category\List.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n\r\n\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 51 "..\..\Views\Category\List.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 55 "..\..\Views\Category\List.cshtml"
                   Write(Html.DisplayFor(modelItem => item.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n\r\n                    <td>\r\n                        " +
"\r\n                        <a");

WriteLiteral(" class=\"btn-sm btn btn-default\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1312), Tuple.Create("\"", 1358)
            
            #line 60 "..\..\Views\Category\List.cshtml"
, Tuple.Create(Tuple.Create("", 1319), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Category.Edit(item.Id))
            
            #line default
            #line hidden
, 1319), false)
);

WriteLiteral("\r\n                           type=\"button\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n                            ویرایش\r\n                        </a>\r\n        " +
"                |\r\n                        <a");

WriteLiteral(" class=\"btn-sm btn btn-default\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1610), Tuple.Create("\"", 1659)
            
            #line 66 "..\..\Views\Category\List.cshtml"
, Tuple.Create(Tuple.Create("", 1617), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Category.Details(item.Id))
            
            #line default
            #line hidden
, 1617), false)
);

WriteLiteral("\r\n                           type=\"button\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-info-circle\"");

WriteLiteral("></i>\r\n                            جزییات\r\n                        </a>\r\n        " +
"                |\r\n                        <a");

WriteLiteral(" class=\"btn-sm btn btn-danger\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1917), Tuple.Create("\"", 1965)
            
            #line 72 "..\..\Views\Category\List.cshtml"
, Tuple.Create(Tuple.Create("", 1924), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Category.Delete(item.Id))
            
            #line default
            #line hidden
, 1924), false)
);

WriteLiteral("\r\n                           type=\"button\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-trash-o\"");

WriteLiteral("></i>\r\n                            حذف\r\n                        </a>\r\n\r\n         " +
"           </td>\r\n\r\n                </tr>\r\n");

            
            #line 81 "..\..\Views\Category\List.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </table>\r\n\r\n\r\n\r\n    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 93 "..\..\Views\Category\List.cshtml"
           Write(Html.ActionLink("ایجاد جدید", "Create", new { Controller = "Category" }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 96 "..\..\Views\Category\List.cshtml"
           Write(Html.ActionLink("مشاهده دسته ها", "Item", new {Controller = "Category"}, new {@class = "btn btn-default"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
