#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/List.cshtml")]
    public partial class _Views_Category_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Advertise.ViewModel.Models.Categories.Category.CategoryListViewModel>>
    {
        public _Views_Category_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Category\List.cshtml"
  
    ViewBag.Title = "List";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>List</h2>\r\n\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Category\List.cshtml"
Write(Html.ActionLink("Create New", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayNameFor(model => model.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayNameFor(model => model.ImageFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayNameFor(model => model.ParentPath));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayNameFor(model => model.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 35 "..\..\Views\Category\List.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 38 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 41 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 47 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.ImageFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 50 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.ParentPath));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 53 "..\..\Views\Category\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 56 "..\..\Views\Category\List.cshtml"
       Write(Html.ActionLink("Edit", "Edit", new { id=item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 57 "..\..\Views\Category\List.cshtml"
       Write(Html.ActionLink("Details", "Details", new { id=item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 58 "..\..\Views\Category\List.cshtml"
       Write(Html.ActionLink("Delete", "Delete", new { id=item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 61 "..\..\Views\Category\List.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
