#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.RazorHelpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\RazorHelpers\NotyBuilder.cshtml"
    using Advertise.Common.Noty;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class NotyBuilder : System.Web.WebPages.HelperPage
    {

#line 6 "..\..\RazorHelpers\NotyBuilder.cshtml"
public static System.Web.WebPages.HelperResult ShowNotyMessages(Noty notyInput)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 7 "..\..\RazorHelpers\NotyBuilder.cshtml"
 
if (notyInput == null)
{
    return;
}



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        $( document ).ready(function() {\r\n\r\n");


#line 16 "..\..\RazorHelpers\NotyBuilder.cshtml"
        

#line default
#line hidden

#line 16 "..\..\RazorHelpers\NotyBuilder.cshtml"
         foreach (var message in notyInput.NotyMessages)
            {
                

#line default
#line hidden

#line 58 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                           
                if (message.Type == AlertType.Information)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, "infoNoty(\'");


#line 61 "..\..\RazorHelpers\NotyBuilder.cshtml"
  WriteTo(__razor_helper_writer, message.Message);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n");


#line 62 "..\..\RazorHelpers\NotyBuilder.cshtml"
                }
            if (message.Type == AlertType.Error)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, "dangerNoty(\'");


#line 65 "..\..\RazorHelpers\NotyBuilder.cshtml"
    WriteTo(__razor_helper_writer, message.Message);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n");


#line 66 "..\..\RazorHelpers\NotyBuilder.cshtml"
                }
                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n    });\r\n\r\n    </script>\r\n");


#line 72 "..\..\RazorHelpers\NotyBuilder.cshtml"


#line default
#line hidden
});

#line 72 "..\..\RazorHelpers\NotyBuilder.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
