#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Post/Index.cshtml")]
    public partial class _Views_Post_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Post_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Post\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- Single button -->\r\n<div");

WriteLiteral(" class=\"row \"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <!-- Brand and toggle get grouped for better mobile display -->\r\n " +
"           <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle collapsed\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#bs-example-navbar-collapse-1\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n                <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">صفحه اصلی</a>\r\n            </div>\r\n\r\n            <!-- Collect the nav links, for" +
"ms, and other content for toggling -->\r\n            <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" id=\"bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">خوراک <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">رستوران<span");

WriteLiteral(" class=\"badge\"");

WriteLiteral(">5</span></a></li>\r\n                            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">فست فود<span");

WriteLiteral(" class=\"badge\"");

WriteLiteral(">1</span></a></li>\r\n                            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">تهیه غذا <span");

WriteLiteral(" class=\"badge\"");

WriteLiteral(">3</span></a></li>\r\n\r\n                            ");

WriteLiteral("\r\n                        </ul>\r\n                    </li>\r\n                    <" +
"li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">پوشاک <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">کیف</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">کفش</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">مانتو</a></li>\r\n                            ");

WriteLiteral("\r\n                        </ul>\r\n                    </li>\r\n                </ul>" +
"\r\n                <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">مسکن <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" ng-repeat=\"model\"");

WriteLiteral(">\r\n                            \r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("></a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">آپارتمان</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">باغ</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">تجاری</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Post\Index.cshtml"
                                       Write(ViewBag.Iman);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\Post\Index.cshtml"
                                       Write(ViewBag.AR);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                            ");

WriteLiteral("\r\n                            ");

WriteLiteral("\r\n                        </ul>\r\n                    </li>\r\n                </ul>" +
"\r\n                <form");

WriteLiteral(" class=\"navbar-form navbar-left\"");

WriteLiteral(" role=\"search\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"جستجو\"");

WriteLiteral(" size=\"100px\"");

WriteLiteral(">\r\n                    </div>\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">جستجو</button>\r\n                </form>\r\n\r\n            </div><!-- /.navbar-colla" +
"pse -->\r\n        </div><!-- /.container-fluid -->\r\n    </nav>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-sm-6 col-md-4\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"thumbnail\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4561), Tuple.Create("\"", 4591)
, Tuple.Create(Tuple.Create("", 4567), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/Pic.jpg")
, 4567), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">\r\n                <h3><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">طرح و پردازش غدیر</a></h3>\r\n                <h5><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">نرم افزار اطلس</a></h5>\r\n                <p>مبلغ :12333</p>\r\n                <p>" +
"توضیحات</p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
